Repository palantir/conjure-java, pull requests merged in 2019-10, with the labels that each got.

#580 Create .changelog.yml
  .changelog.yml
Labels: merge when ready, no changelog

#595 Fix conjure-undertow handling complex query parameter collections
  changelog/@unreleased/pr-595.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceRetrofit.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UndertowEteService.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceHandlerGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowTypeFunctions.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/EteResource.java
  conjure-java-core/src/test/resources/ete-service.yml
  conjure-java-core/src/test/resources/example-service.yml
  conjure-java-core/src/test/resources/test/api/TestService.java.jersey
  conjure-java-core/src/test/resources/test/api/TestService.java.jersey_require_not_null
  conjure-java-core/src/test/resources/test/api/TestService.java.undertow
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit_completable_future
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit_listenable_future
Labels: merge when ready

#589 Errors are logged from the ConjureExceptions class
  changelog/@unreleased/pr-589.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptions.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/HttpServerExchanges.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptionHandlerTest.java
Labels: merge when ready

#603 Improve BinaryResponseBody javadoc to answer common questions
  conjure-undertow-lib/src/main/java/com/palantir/conjure/java/undertow/lib/BinaryResponseBody.java
Labels: merge when ready, no changelog

#615 Propagate 401s
  changelog/@unreleased/pr-615.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptions.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptionHandlerTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready
