Repository palantir/conjure-java, pull requests merged in 2019-08, with the labels that each got.

#465 [improvement] Adds a visitor builder for union type visitors
  changelog/@unreleased/pr-465.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/SingleUnion.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/Union.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
Labels: autorelease, merge when ready

#480 conjure-undertow supports OPTIONS requests.
  changelog/@unreleased/pr-480.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureHandler.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/OptionsHandler.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureHandlerBuilderTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/OptionsRequestTest.java
Labels: autorelease, merge when ready

#483 [fix] Add @Override annotations to visitor builder methods
  changelog/@unreleased/pr-483.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/SingleUnion.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/Union.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
Labels: merge when ready

#485 [fix] Makes union type visitor handlers immutable in build method.
  changelog/@unreleased/pr-485.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/SingleUnion.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/Union.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
Labels: autorelease, merge when ready

#425 [improvement] conjure-undertow endpoints provide tracing spans around body serde
  changelog/@unreleased/pr-425.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/TracedEncoding.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/TracedEncodingTest.java
Labels: autorelease, merge when ready

#505 Make verifier use random port
  conjure-java-server-verifier/src/test/java/com/palantir/conjure/java/verification/server/undertest/UndertowServerUnderTestExtension.java
  conjure-java-server-verifier/src/test/resources/config.yml
Labels: merge when ready, no changelog

#499 break: Match parameter order between jax-rs and retrofit clients
  changelog/@unreleased/pr-499.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceRetrofit.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/DefaultTypeValueVisitor.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/DefaultableTypeVisitor.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Retrofit2ServiceGenerator.java
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit_completable_future
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit_listenable_future
Labels: merge when ready
