Repository palantir/conjure-java, pull requests merged in 2019-07, with the labels that each got.

#446 Deserialize null fields as empty collections
  changelog/@unreleased/pr-446.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/binary/OptionalExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/AliasAsMapKeyExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/AnyMapExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/CovariantListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/CovariantOptionalExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ExternalLongExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/MapExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/OptionalExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/PrimitiveOptionalsExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SetExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/MissingFieldWireFormatTests.java
Labels: autorelease, merge when ready

#444 [improvement] ConjureAsyncRequestProcessing invokes 'nextListener.proceed()' in finally
  changelog/@unreleased/pr-444.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureAsyncRequestProcessing.java
Labels: merge when ready

#459 Fix exception message wording on deserialization failure
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/Encodings.java
Labels: merge when ready, no changelog

#461 Migrate to Junit5
  conjure-java-client-verifier/build.gradle
  conjure-java-core/build.gradle
  conjure-java-core/src/test/java/com/palantir/conjure/java/AsyncRequestProcessingTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/BinaryExampleTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/CovariantsTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/JerseyServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/JerseyServiceGeneratorTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/Retrofit2ServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/Retrofit2ServiceGeneratorTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceGeneratorTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/AliasTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/BeanSerdeIntegrationTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/EnumTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/MissingFieldWireFormatTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/NoFieldBeanTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/NullFieldWireFormatTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/ObjectGeneratorTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/WireFormatTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/util/GoetheTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/util/JavadocTest.java
  conjure-java-server-verifier/build.gradle
  conjure-java-server-verifier/src/test/java/com/palantir/conjure/java/verification/server/AutoDeserializeTest.java
  conjure-java-server-verifier/src/test/java/com/palantir/conjure/java/verification/server/VerificationClientExtension.java
  conjure-java-server-verifier/src/test/java/com/palantir/conjure/java/verification/server/VerificationClients.java
  conjure-java-server-verifier/src/test/java/com/palantir/conjure/java/verification/server/undertest/UndertowServerUnderTestExtension.java
  conjure-java-undertow-runtime/build.gradle
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/lib/SerializableErrorTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/AuthTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/BearerTokenLoggingTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDeTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptionHandlerTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureHandlerBuilderTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureHandlerTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/EncodingsTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/LoggingContextHandlerTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/MarkerCallbackTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/NoCachingResponseHandlerTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/PlainSerDeTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/TypeMarkersTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/WebSecurityHandlerTest.java
  conjure-java/build.gradle
  conjure-java/src/test/java/com/palantir/conjure/java/cli/ConjureJavaCliTest.java
  conjure-lib/build.gradle
  conjure-lib/src/test/java/com/palantir/conjure/java/lib/BytesTests.java
  conjure-lib/src/test/java/com/palantir/conjure/java/lib/SafeLongTests.java
  versions.lock
  versions.props
Labels: no changelog

#449 Implement SafeExchangeCompletionListener utility
  changelog/@unreleased/pr-449.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureAsyncRequestProcessing.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/SafeExchangeCompletionListener.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/SafeExchangeCompletionListenerTest.java
Labels: merge when ready

#473 Undertow async result exceptions are logged with the correct traceId
  changelog/@unreleased/pr-473.v2.yml
  conjure-java-core/build.gradle
  conjure-java-core/src/integrationInput/java/com/palantir/product/AsyncRequestProcessingTestService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/AsyncRequestProcessingTestServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UndertowAsyncRequestProcessingTestService.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/AsyncRequestProcessingTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/AsyncRequestProcessingTestResource.java
  conjure-java-core/src/test/resources/async-request-processing-test.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureAsyncRequestProcessing.java
  versions.lock
Labels: merge when ready
