Repository palantir/conjure-java, pull requests merged in 2019-12, with the labels that each got.

#668 Fix dead link
  readme.md
Labels: merge when ready, no changelog

#641 Break: Always generate ListenableFuture variant of retrofit interfaces
  changelog/@unreleased/pr-641.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceRetrofit.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceRetrofit.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceRetrofit.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/FeatureFlags.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Retrofit2ServiceGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/JerseyServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/Retrofit2ServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/Retrofit2ServiceGeneratorTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceEteTest.java
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit_completable_future
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit_listenable_future
  conjure-java/src/main/java/com/palantir/conjure/java/cli/CliConfiguration.java
  conjure-java/src/main/java/com/palantir/conjure/java/cli/ConjureJavaCli.java
  conjure-java/src/test/java/com/palantir/conjure/java/cli/ConjureJavaCliTest.java
Labels: merge when ready

#643 Break: Correctly generate optional<binary> fields as Optional<ResponseBody> return type in retrofit client
  changelog/@unreleased/pr-643.v2.yml
  conjure-java-core/build.gradle
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceRetrofit.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Retrofit2ServiceGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/JerseyServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceEteTest.java
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit
  versions.lock
  versions.props
Labels: merge when ready

#686 Fix Content-Type comparison to be case-insensitive
  changelog/@unreleased/pr-686.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/Encoding.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/Encodings.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/EncodingsTest.java
Labels: autorelease, merge when ready

#683 conjure-undertow non-service-exceptions are no longer wrapped
  changelog/@unreleased/pr-683.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptions.java
Labels: merge when ready

#687 Document `--nonNullCollections` in the readme
  readme.md
Labels: merge when ready, no changelog

#688 Document strictObjects in readme
  readme.md
Labels: merge when ready, no changelog
