Repository palantir/conjure-java, pull requests merged in 2020-10, with the labels that each got.

#1103 fix #573: Unions with type `unknown` compile as expected
  changelog/@unreleased/pr-1103.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UnionWithUnknownString.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/UnionWithUnknownString.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/util/JavaNameSanitizer.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/WireFormatTests.java
  conjure-java-core/src/test/resources/example-types.yml
Labels: merge when ready

#1111 Pin jackson to 2.11.1
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#1086 Annotate enums with error-prone Immutable
  changelog/@unreleased/pr-1086.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SimpleEnum.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SimpleEnum.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/EnumGenerator.java
Labels: autorelease, merge when ready

#1113 fix flag counting logic
  conjure-java/src/main/java/com/palantir/conjure/java/cli/CliConfiguration.java
Labels: merge when ready, no changelog

#1115 ConjureJavaCli creates generators as needed
  conjure-java/src/main/java/com/palantir/conjure/java/cli/ConjureJavaCli.java
Labels: merge when ready, no changelog

#1102 fix #1099: conjure-undertow correctly dealiases binary responses
  changelog/@unreleased/pr-1102.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/AliasOptionalDoubleAliasedBinaryResult.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/AliasedBinaryResult.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DialogueEteBinaryEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DoubleAliasedBinaryResult.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceRetrofit.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UndertowEteBinaryService.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Retrofit2ServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/ServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowRequestBodyClassNameVisitor.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowReturnValueClassNameVisitor.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceHandlerGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowTypeFunctions.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DialogueServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/DefaultClassNameVisitor.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/ErrorGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/ObjectGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/ReturnTypeClassNameVisitor.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/SpecializeBinaryClassNameVisitor.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/TypeGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/TypeMapper.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/util/TypeFunctions.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/visitor/DialogueClassVisitor.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/EteBinaryResource.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowBinaryResource.java
  conjure-java-core/src/test/resources/ete-binary.yml
  conjure-java-core/src/test/resources/test/api/TestService.java.jersey
  conjure-java-core/src/test/resources/test/api/TestService.java.jersey.prefix
  conjure-java-core/src/test/resources/test/api/TestService.java.jersey_require_not_null
  conjure-java-core/src/test/resources/test/api/TestService.java.undertow
  conjure-java-core/src/test/resources/test/api/TestService.java.undertow.prefix
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow.prefix
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit.prefix
Labels: autorelease, merge when ready

#1132 cache hashcode in bytes
  changelog/@unreleased/pr-1132.v2.yml
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/Bytes.java
Labels: autorelease, merge when ready

#1143 Upgrade conjure IR version
  changelog/@unreleased/pr-1143.v2.yml
  versions.lock
  versions.props
Labels: merge when ready

#1144 Support conjure tags in place of cumbersome java annotation-based markers
  changelog/@unreleased/pr-1144.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/NameCollisionServiceEndpoints.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/ConjureTags.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceHandlerGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowTypeFunctions.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/ConjureTagsTest.java
  conjure-java-core/src/test/resources/dangerous-name-service.yml
  conjure-java-core/src/test/resources/example-service.yml
  conjure-java-core/src/test/resources/test/api/AsyncMarkers.java.undertow
  conjure-java-core/src/test/resources/test/api/AsyncMarkers.java.undertow.async
  conjure-java-core/src/test/resources/test/api/AsyncMarkersEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/AsyncMarkersEndpoints.java.undertow.async
  conjure-java-core/src/test/resources/test/api/TestService.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/TestService.java.jersey
  conjure-java-core/src/test/resources/test/api/TestService.java.jersey.prefix
  conjure-java-core/src/test/resources/test/api/TestService.java.jersey_require_not_null
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow.prefix
  conjure-java-core/src/test/resources/undertow-async-endpoint.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ParamMarker.java
  readme.md
Labels: autorelease, merge when ready

#1145 Undertow Endpoints provide tags when defined
  changelog/@unreleased/pr-1145.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/AsyncRequestProcessingTestServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/NameCollisionServiceEndpoints.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceHandlerGenerator.java
  conjure-java-core/src/test/resources/ete-service.yml
  conjure-java-core/src/test/resources/test/api/AsyncMarkersEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/AsyncMarkersEndpoints.java.undertow.async
  conjure-java-core/src/test/resources/test/api/CookieServiceEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow.binary
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow.prefix
  conjure-undertow-lib/src/main/java/com/palantir/conjure/java/undertow/lib/Endpoint.java
Labels: autorelease, merge when ready
