Repository palantir/conjure-java, pull requests merged in 2020-02, with the labels that each got.

#727 Remove workaround for CBOR closing streams
  changelog/@unreleased/pr-727.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/Encodings.java
Labels: merge when ready

#728 Support enum value, union type, and bean field deprecation
  build.gradle
  changelog/@unreleased/pr-728.v2.yml
  conjure-java-core/build.gradle
  conjure-java-core/src/integrationInput/java/com/palantir/product/ConjureErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/Union.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/Union.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/ConjureAnnotations.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/ServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/EnumGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/util/Javadoc.java
  conjure-java-core/src/test/resources/example-types.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#733 Fix empty unions
  changelog/@unreleased/pr-733.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyUnionTypeExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/EmptyUnionTypeExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
  conjure-java-core/src/test/resources/example-types.yml
Labels: autorelease, merge when ready

#752 [Stacked] dialogue supports cookie auth
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Auth.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/Auth.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/ParameterTypeMapper.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/DialogueServiceGeneratorTests.java
  conjure-java-core/src/test/resources/test/api/AsyncCookieService.java.dialogue
  conjure-java-core/src/test/resources/test/api/BlockingCookieService.java.dialogue
  conjure-java-core/src/test/resources/test/api/DialogueCookieService.java.dialogue
Labels: merge when ready, no changelog

#756 [Stacked] Dialogue add preliminary binary support
  conjure-java-core/build.gradle
  conjure-java-core/src/integrationInput/java/com/palantir/product/AsyncEteBinaryService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/BlockingEteBinaryService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DialogueEteBinaryService.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DialogueServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/visitor/ClassVisitor.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/DialogueServiceGeneratorTests.java
  conjure-java-core/src/test/resources/test/api/DialogueCookieService.java.dialogue
  versions.lock
Labels: merge when ready

#763 dialogue properly supports optionalInt and optionalDouble
  build.gradle
  changelog/@unreleased/pr-763.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/test/resources/test/api/DialogueTestService.java.dialogue
  conjure-java-core/src/test/resources/test/api/DialogueTestService.java.dialogue.prefix
Labels: autorelease, merge when ready

#789 Tweak dialogue codegen
  .gitattributes
  changelog/@unreleased/pr-789.v2.yml
  conjure-java-client-verifier/src/test/java/com/palantir/conjure/java/compliance/VerificationClients.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/AsyncEmptyPathService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/AsyncEteBinaryService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/AsyncEteService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/BlockingEmptyPathService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/BlockingEteBinaryService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/BlockingEteService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DialogueEmptyPathEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DialogueEmptyPathService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DialogueEteBinaryEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DialogueEteBinaryService.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DialogueEteEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DialogueEteService.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/BlockingGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DialogueEndpointsGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DialogueInterfaceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DialogueServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/Names.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/StaticFactoryMethodGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/DialogueServiceGeneratorTests.java
  conjure-java-core/src/test/resources/test/api/AsyncCookieService.java.dialogue
  conjure-java-core/src/test/resources/test/api/AsyncTestService.java.dialogue
  conjure-java-core/src/test/resources/test/api/AsyncTestService.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/BlockingCookieService.java.dialogue
  conjure-java-core/src/test/resources/test/api/BlockingTestService.java.dialogue
  conjure-java-core/src/test/resources/test/api/BlockingTestService.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/DialogueCookieEndpoints.java.dialogue
  conjure-java-core/src/test/resources/test/api/DialogueCookieService.java.dialogue
  conjure-java-core/src/test/resources/test/api/DialogueTestEndpoints.java.dialogue
  conjure-java-core/src/test/resources/test/api/DialogueTestEndpoints.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/DialogueTestService.java.dialogue
  conjure-java-core/src/test/resources/test/api/DialogueTestService.java.dialogue.prefix
Labels: autorelease, merge when ready

#790 dialogue: FooServiceBlocking instead of BlockingFooService
  changelog/@unreleased/pr-790.v2.yml
  conjure-java-client-verifier/src/test/java/com/palantir/conjure/java/compliance/AutoDeserializeTest.java
  conjure-java-client-verifier/src/test/java/com/palantir/conjure/java/compliance/VerificationClients.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceBlocking.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/Names.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/DialogueServiceGeneratorTests.java
  conjure-java-core/src/test/resources/test/api/CookieServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/CookieServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue.prefix
Labels: autorelease, merge when ready
