Repository palantir/conjure-java, pull requests merged in 2020-03, with the labels that each got.

#812 conjure-undertow handles multi-value accept headers
  changelog/@unreleased/pr-812.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDeTest.java
Labels: autorelease, merge when ready

#815 Update codegen to support Dialogue 0.12.2
  changelog/@unreleased/pr-815.v2.yml
  conjure-java-client-verifier/src/test/java/com/palantir/conjure/java/compliance/VerificationClients.java
  conjure-java-client-verifier/src/test/java/com/palantir/conjure/java/compliance/VerificationServerRule.java
  conjure-java-core/build.gradle
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceBlocking.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/BlockingGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/JerseyServiceEteTest.java
  conjure-java-core/src/test/resources/test/api/CookieServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/CookieServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue.prefix
  conjure-lib/build.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#819 Dialogue service generator avoids method references to the same type
  changelog/@unreleased/pr-819.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceAsync.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/test/resources/test/api/CookieServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue.prefix
  versions.lock
  versions.props
Labels: merge when ready

#824 Improve gitattributes
  .gitattributes
Labels: merge when ready, no changelog

#823 Update conjure-undertow default encodings
  changelog/@unreleased/pr-823.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureUndertowRuntime.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/Encodings.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/EncodingsTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#825 Fix annotating type rather than parameter with Nonnull
  changelog/@unreleased/pr-825.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/Parameters.java
Labels: autorelease, merge when ready

#830 Dialogue endpoints use version '0.0.0' over 'unknown' by default
  changelog/@unreleased/pr-830.v2.yml
  conjure-java/src/main/java/com/palantir/conjure/java/cli/ConjureJavaCli.java
Labels: autorelease, merge when ready

#828 Dialogue correctly handles optional binary responses
  changelog/@unreleased/pr-828.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceBlocking.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DialogueServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/visitor/DialogueClassVisitor.java
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue.prefix
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#840 Prevent ISE when rst_stream is received prior to async register-callback
  changelog/@unreleased/pr-840.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureAsyncRequestProcessing.java
Labels: autorelease, merge when ready

#842 dialogue: suppress deprecation
  changelog/@unreleased/pr-842.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/BlockingGenerator.java
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue.prefix
Labels: autorelease, merge when ready

#843 s/deprecated/deprecation/
  changelog/@unreleased/pr-843.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/BlockingGenerator.java
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue.prefix
Labels: autorelease, merge when ready

#849 Document how to recreate test files.
  CONTRIBUTING.md
Labels: merge when ready, no changelog

#768 On enum, generate values() similar to java enums.
  changelog/@unreleased/pr-768.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SimpleEnum.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SimpleEnum.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/EnumGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/EnumTests.java
Labels: autorelease, merge when ready

#850 Suppress deprecation building enum values list when necessary
  changelog/@unreleased/pr-850.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/EnumExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/EnumGenerator.java
Labels: autorelease, merge when ready

#856 add prefix to dialogue defined variables
  changelog/@unreleased/pr-856.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceBlocking.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/BlockingGenerator.java
  conjure-java-core/src/test/resources/test/api/CookieServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/CookieServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceBlocking.java.dialogue.prefix
Labels: autorelease, merge when ready

#860 Fix dialogue auth header serialization
  changelog/@unreleased/pr-860.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceAsync.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestServiceAsync.java.dialogue.prefix
Labels: autorelease, merge when ready

#861 Fix Dialogue cookie auth
  changelog/@unreleased/pr-861.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/AsyncGenerator.java
  conjure-java-core/src/test/resources/test/api/CookieServiceAsync.java.dialogue
Labels: autorelease, merge when ready

#862 Add cookie service to ete out for dialogue
  conjure-java-core/src/integrationInput/java/com/palantir/product/CookieServiceAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/CookieServiceBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DialogueCookieEndpoints.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/DialogueServiceGeneratorTests.java
Labels: merge when ready, no changelog
