Repository palantir/conjure-java, pull requests merged in 2022-11, with the labels that each got.

#1910 Add form data example to readme
  conjure-undertow-annotations/readme.md
Labels: merge when ready, no changelog

#1919 Performance: faster enum equals method
  changelog/@unreleased/pr-1919.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SimpleEnum.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SimpleEnum.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/EnumGenerator.java
Labels: merge when ready, autorelease

#1921 Always log QosException at info
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptions.java
Labels: merge when ready, no changelog, autorelease
