Repository palantir/conjure-java, pull requests merged in 2022-02, with the labels that each got.

#1629 [undertow-annotations] Handle query params with primitive types
  changelog/@unreleased/pr-1629.v2.yml
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/generate/ConjureUndertowEndpointsGenerator.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/ConjureUndertowAnnotationProcessorTest.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/PrimitiveQueryParams.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/PrimitiveQueryParamsEndpoints.java.generated
Labels: merge when ready

#1632 [undertow-annotations] Add default decoders for header, query, and path params
  changelog/@unreleased/pr-1632.v2.yml
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/Handle.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/ParamDecoders.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/DefaultDecoderNames.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParamTypesResolver.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/ConjureUndertowAnnotationProcessorTest.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/data/DefaultDecoderNamesTest.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/DefaultDecoderService.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/DefaultDecoderServiceEndpoints.java.generated
Labels: merge when ready, autorelease

#1638 Clean up verbiage in Handle.java s/encoder/decoder
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/Handle.java
Labels: merge when ready, no changelog

#1637 Add staged builder missing overrides
  changelog/@unreleased/pr-1637.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/MultipleOrderedStages.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/OneField.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/ConjureAnnotations.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
Labels: autorelease

#1639 Undertow processor default decoder logic is based on names
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/DefaultDecoderNames.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/data/DefaultDecoderNamesTest.java
Labels: merge when ready, no changelog

#1640 Add annotation for cookie params
  changelog/@unreleased/pr-1640.v2.yml
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/BearerTokenCookieDeserializer.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/CookieDeserializer.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/Handle.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/ParamDecoder.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/ParamDecoders.java
  conjure-undertow-processor-example/src/main/java/com/palantir/conjure/java/undertow/example/ExampleService.java
  conjure-undertow-processor-example/src/test/java/com/palantir/conjure/java/undertow/example/ExampleResource.java
  conjure-undertow-processor-example/src/test/java/com/palantir/conjure/java/undertow/example/ExampleServiceTest.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParamTypesResolver.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParameterType.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/generate/ConjureUndertowEndpointsGenerator.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/ConjureUndertowAnnotationProcessorTest.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/CookieParams.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/CookieParamsEndpoints.java.generated
Labels: merge when ready, autorelease

#1641 Support `T valueOf(String)` and `new T(String)` default decoders
  changelog/@unreleased/pr-1641.v2.yml
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/ParamDecoders.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/DefaultDecoderNames.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParamTypesResolver.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/generate/ConjureUndertowEndpointsGenerator.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/data/DefaultDecoderNamesTest.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/DefaultDecoderService.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/DefaultDecoderServiceEndpoints.java.generated
Labels: merge when ready, autorelease

#1648 Fix annotation processor optional-complex cookie deserialization
  changelog/@unreleased/pr-1648.v2.yml
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/ParamDecoders.java
  conjure-undertow-processor-example/src/main/java/com/palantir/conjure/java/undertow/example/ExampleService.java
  conjure-undertow-processor-example/src/test/java/com/palantir/conjure/java/undertow/example/ExampleResource.java
  conjure-undertow-processor-example/src/test/java/com/palantir/conjure/java/undertow/example/ExampleServiceTest.java
Labels: merge when ready, autorelease

#1650 Provide Endpoints to BodySerde factories
  changelog/@unreleased/pr-1650.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/AsyncRequestProcessingTestServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/NameCollisionServiceEndpoints.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceHandlerGenerator.java
  conjure-java-core/src/test/resources/test/api/AsyncMarkersEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/AsyncMarkersEndpoints.java.undertow.async
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/TestServiceEndpoints.java.undertow.prefix
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/Encoding.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/TracedEncoding.java
  conjure-undertow-lib/src/main/java/com/palantir/conjure/java/undertow/lib/BodySerDe.java
Labels: merge when ready

#1653 Provide Endpoints to conjure-undertow-annotations serde factories
  changelog/@unreleased/pr-1653.v2.yml
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/DefaultSerDe.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/DeserializerFactory.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/SerializerFactory.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/generate/ConjureUndertowEndpointsGenerator.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/CookieParamsEndpoints.java.generated
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/DefaultDecoderServiceEndpoints.java.generated
Labels: merge when ready, autorelease

#1654 The undertow annotation processor supports globbed path ends
  changelog/@unreleased/pr-1654.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureHandler.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/GlobRetainingDecodingHandler.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/Handle.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/PathMultiParamDeserializer.java
  conjure-undertow-processor-example/build.gradle
  conjure-undertow-processor-example/src/main/java/com/palantir/conjure/java/undertow/example/TrailingGlobResource.java
  conjure-undertow-processor-example/src/test/java/com/palantir/conjure/java/undertow/example/TrailingGlobTest.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/EndpointDefinitions.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParamTypesResolver.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParameterType.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/generate/ConjureUndertowEndpointsGenerator.java
Labels: merge when ready, autorelease

#1655 Add conjure-undertow-annotations docs
  conjure-undertow-annotations/readme.md
  readme.md
Labels: merge when ready, no changelog

#1657 Delete DefaultCollectionParamDecoder in favor of DefaultParamDecoder
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/DefaultCollectionParamDecoder.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/Handle.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParamTypesResolver.java
Labels: no changelog

#1658 Remove HttpPath cruft borrowed from the dialogue-processor
  conjure-undertow-processor/build.gradle
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/EndpointDefinitions.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/HttpPath.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/HttpPathParser.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/HttpPathSegment.java
Labels: merge when ready, no changelog

#1659 PathMultiParam javadocs
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/GlobRetainingDecodingHandler.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/Handle.java
Labels: merge when ready, no changelog

#1660 [processor] fix primitive body deserializer handling
  changelog/@unreleased/pr-1660.v2.yml
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/generate/ConjureUndertowEndpointsGenerator.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/ConjureUndertowAnnotationProcessorTest.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/PrimitiveBodyParam.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/PrimitiveBodyParamEndpoints.java.generated
Labels: merge when ready, autorelease

#1662 Fix code examples in readme
  conjure-undertow-annotations/readme.md
Labels: no changelog

#1666 Simplify integer hashcode
  conjure-java-core/src/integrationInput/java/com/palantir/product/IntegerExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ReservedKeyExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/Union.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/strict/SingleFieldNotStrict.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/IntegerExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ReservedKeyExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/Union.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/MethodSpecs.java
Labels: merge when ready, no changelog

#1669 Test coverage for missing annotations
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ArgumentTypesResolver.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/EndpointDefinitions.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/ConjureUndertowAnnotationProcessorTest.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/ParameterNotAnnotated.java
Labels: merge when ready, no changelog

#1667 [processor] Add support for safe logging annotations
  changelog/@unreleased/pr-1667.v2.yml
  conjure-undertow-processor/build.gradle
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/EndpointDefinitions.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/InstanceVariables.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParamTypesResolver.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParameterType.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParameterTypeVisitors.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/generate/ConjureUndertowEndpointsGenerator.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/ConjureUndertowAnnotationProcessorTest.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/NameClashContextParam.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/NameClashExchangeParam.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/PrimitiveQueryParams.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/SafeLoggableAuthCookieParam.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/SafeLoggableAuthHeaderParam.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/SafeLoggableParams.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/CookieParamsEndpoints.java.generated
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/DefaultDecoderServiceEndpoints.java.generated
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/PrimitiveQueryParamsEndpoints.java.generated
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/SafeLoggableParamsEndpoints.java.generated
  versions.lock
Labels: merge when ready, autorelease

#1671 test consuming raw exchange
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/ConsumesExchange.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/ConsumesExchangeEndpoints.java.generated
Labels: merge when ready, no changelog

#1672 Avoid increasing the minimum error-prone version for consumers
  versions.lock
  versions.props
Labels: merge when ready, no changelog, autorelease
