Repository palantir/conjure-java, pull requests merged in 2022-07, with the labels that each got.

#1840 Use consistent name for auth parameters
  changelog/@unreleased/pr-1840.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Auth.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Retrofit2ServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceHandlerGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceInterfaceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/util/JavaNameSanitizer.java
  conjure-java-core/src/test/resources/test/api/CookieService.java.undertow
  conjure-java-core/src/test/resources/test/api/CookieServiceEndpoints.java.undertow
Labels: merge when ready

#1842 Generated equals uses memoizedHashCode if available
  changelog/@unreleased/pr-1842.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/AliasAsMapKeyExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/AnyMapExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/CollectionsTestObject.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/CovariantListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/CovariantOptionalExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/DateTimeExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ExternalLongExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/MapExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/MultipleFieldsOnlyFinalStage.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/MultipleOrderedStages.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/PrimitiveOptionalsExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ReservedKeyExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/RiskyNames.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SetExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/AliasAsMapKeyExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/AnyMapExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/CovariantListExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/CovariantOptionalExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/DateTimeExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ExternalLongExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/MapExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/PrimitiveOptionalsExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ReservedKeyExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/RiskyNames.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SetExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/MethodSpecs.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/ObjectMethodsTest.java
Labels: merge when ready, autorelease

#1843 Move Goethe to implementation dependencies
  conjure-java-core/build.gradle
Labels: merge when ready, no changelog

#1852 Collection setters use constructor when clearing
  changelog/@unreleased/pr-1852.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/AliasAsMapKeyExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/AnyMapExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/CollectionsTestObject.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/CovariantListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ExternalLongExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/MapExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/MultipleFieldsOnlyFinalStage.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/MultipleOrderedStages.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SetExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/AliasAsMapKeyExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/AnyMapExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/CovariantListExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ExternalLongExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/MapExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SetExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureCollections.java
Labels: merge when ready, autorelease

#1854 Compare content-type case insensitive
  changelog/@unreleased/pr-1854.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDeTest.java
Labels: merge when ready, autorelease
