Repository palantir/conjure-java, pull requests merged in 2023-03, with the labels that each got.

#1974 Fix alias-of-optional codegen with safety info
  changelog/@unreleased/pr-1974.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/OptionalDoubleAlias.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/OptionalDoubleAlias.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java
  conjure-java-core/src/test/resources/example-types.yml
Labels: merge when ready, autorelease

#1979 Methods in staged builder interfaces are ordered deterministically
  changelog/@unreleased/pr-1979.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/MultipleOrderedStages.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
Labels: merge when ready, autorelease

#1981 Staged Builders: Remove unneeded sort, and only sort arguments of static factory when using staged builders
  changelog/@unreleased/pr-1981.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/MultipleFieldsOneFinalStage.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
  conjure-java-core/src/test/resources/example-staged-types.yml
Labels: merge when ready

#1989 Fix regression causing union visitor primitive functions not to be used when safety is specified
  changelog/@unreleased/pr-1989.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/WireFormatTests.java
  conjure-java-core/src/test/resources/example-types.yml
Labels: merge when ready, autorelease

#1949 Remove unused jaxrs dependency from conjure-lib
  changelog/@unreleased/pr-1949.v2.yml
  conjure-lib/build.gradle
  gradle/verifier.gradle
Labels: merge when ready, autorelease

#1993 verifier.gradle uses the javax ws.rs-api dep rather than jakarta
  gradle/verifier.gradle
Labels: merge when ready, no changelog

#2001 Nullable annotation for cause in ConjureErrors
  changelog/@unreleased/pr-2001.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/another/ConjureErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/another/ConjureJavaOtherErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ConjureErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ConjureJavaErrors.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/ErrorGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/EteErrors.java
Labels: merge when ready, autorelease

#1992 Add strict staged builders
  changelog/@unreleased/pr-1992.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictFourFields.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictMultipleDeprecatedAndUnsafeFields.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictOneCollectionField.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictOneField.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictOneOptionalField.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictThreeFields.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/Options.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/ObjectGeneratorTests.java
  conjure-java-core/src/test/resources/example-strict-staged-types.yml
  conjure-java/src/main/java/com/palantir/conjure/java/cli/ConjureJavaCli.java
  readme.md
Labels: merge when ready, autorelease
