Repository palantir/conjure-java, pull requests merged in 2023-11, with the labels that each got.

#2131 Add test coverage for current Undertow SerializableError serialization behavior
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/lib/SerializableErrorTest.java
Labels: merge when ready, no changelog

#2128 Remove Usage of Retrofit-clients in Tests
  conjure-java-core/build.gradle
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteBinaryServiceRetrofit.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EteServiceRetrofit.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/EteTestServer.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/JerseyServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/Retrofit2ServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/Retrofit2ServiceGeneratorTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceEteTest.java
  conjure-java-core/src/test/resources/logback-test.xml
  readme.md
  versions.lock
Labels: merge when ready, no changelog

#2133 Deconflict Jersey Undertow Tests
  conjure-java-core/src/test/java/com/palantir/conjure/java/EteTestServer.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/JerseyServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceEteTest.java
Labels: merge when ready, no changelog

#2136 Remove Final OkHttp Usage
  conjure-java-core/build.gradle
  conjure-java-core/src/test/java/com/palantir/conjure/java/AsyncRequestProcessingTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/JerseyServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceEteTest.java
  conjure-java-undertow-runtime/build.gradle
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptionHandlerTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureHandlerTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/NoCachingResponseHandlerTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/OptionsRequestTest.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/WebSecurityHandlerTest.java
  versions.lock
Labels: merge when ready, no changelog

#2135 Remove Retrofit Client Generation
  changelog/@unreleased/pr-2135.v2.yml
  conjure-java-core/build.gradle
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyPathServiceRetrofit.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Retrofit2ServiceGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceEteTest.java
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit
  conjure-java-core/src/test/resources/test/api/TestServiceRetrofit.java.retrofit.prefix
  conjure-java/src/main/java/com/palantir/conjure/java/cli/CliConfiguration.java
  conjure-java/src/main/java/com/palantir/conjure/java/cli/ConjureJavaCli.java
  conjure-java/src/test/java/com/palantir/conjure/java/cli/ConjureJavaCliTest.java
  readme.md
  versions.props
Labels: merge when ready, autorelease

#2138 Semantice Merge Conflict Unused Constraint
  versions.props
Labels: merge when ready, no changelog, autorelease
