Repository palantir/conjure-java, pull requests merged in 2023-08, with the labels that each got.

#2084 Downgrade Caffeine to 3.1.6
  versions.lock
  versions.props
Labels: merge when ready, no changelog, autorelease

#2073 Simplify SafeLong implementation
  changelog/@unreleased/pr-2073.v2.yml
  conjure-lib/build.gradle
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/SafeLong.java
Labels: merge when ready, autorelease

#2080 Add StdSerializer and StdDeserializer
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/StdDeserializer.java
  conjure-undertow-annotations/src/main/java/com/palantir/conjure/java/undertow/annotations/StdSerializer.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/PrimitiveBodyParam.java
Labels: merge when ready, no changelog, autorelease

#1913 Enforce explicit dependency constraints
  build.gradle
  conjure-java-client-verifier/build.gradle
  conjure-java-client-verifier/src/test/java/com/palantir/conjure/java/compliance/AutoDeserializeTest.java
  conjure-java-client-verifier/src/test/java/com/palantir/conjure/java/compliance/SingleParamServicesTest.java
  conjure-java-core/build.gradle
  conjure-java-core/src/main/java/com/palantir/conjure/java/Options.java
  conjure-java-server-verifier/build.gradle
  conjure-java-server-verifier/src/test/java/com/palantir/conjure/java/verification/server/AutoDeserializeTest.java
  conjure-java-undertow-runtime/build.gradle
  conjure-java/build.gradle
  conjure-lib/build.gradle
  conjure-undertow-annotations/build.gradle
  conjure-undertow-lib/build.gradle
  conjure-undertow-processor-example/build.gradle
  conjure-undertow-processor/build.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#2096 Add enum visitor builder
  changelog/@unreleased/pr-2096.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SimpleEnum.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/EnumExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SimpleEnum.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/EnumGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/EnumTests.java
Labels: merge when ready, autorelease
