Repository palantir/conjure-java, pull requests merged in 2023-02, with the labels that each got.

#1960 add integration tests that take advantage of safety annotations on external longs
  conjure-java-core/src/integrationInput/java/com/palantir/product/DangerousLongAlias.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ExternalLongAlias.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ExternalLongTestServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ExternalLongUnionExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SafeExternalLongAlias.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SafeExternalLongExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SafeLongAlias.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UndertowExternalLongTestService.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ExternalLongUnionExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SafeExternalLongAlias.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SafeExternalLongExample.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceEteTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/SafetyEvaluatorTest.java
  conjure-java-core/src/test/resources/example-types.yml
  conjure-java-core/src/test/resources/external-long-test-service.yml
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#1965 item setters now have safety annotations
  changelog/@unreleased/pr-1965.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/BearerTokenAliasExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/NestedStringAliasExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/OptionalAlias.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/OptionalExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SingleUnion.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StringAliasExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/BearerTokenAliasExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/NestedStringAliasExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/OptionalAlias.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/OptionalExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SingleUnion.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/StringAliasExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/ConjureAnnotations.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderAuxiliarySettersUtils.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/ErrorGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/Parameters.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
  conjure-java-core/src/test/resources/example-types.yml
Labels: merge when ready, autorelease

#1967 use our own boxing and unboxing logic instead of poet's
  conjure-java-core/src/integrationInput/java/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/UnionTypeExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Retrofit2ServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceHandlerGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowTypeFunctions.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DefaultStaticFactoryMethodGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/ReturnTypeMapper.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderAuxiliarySettersUtils.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/DefaultClassNameVisitor.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/MethodSpecs.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/Parameters.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/util/PrimitiveHelpers.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/WireFormatTests.java
  conjure-java-core/src/test/resources/example-types.yml
Labels: merge when ready, no changelog, autorelease

#1968 remove an extraneous annotation
  conjure-java-core/src/integrationInput/java/com/palantir/product/SafeLongAliasExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SafeLongAliasExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java
  conjure-java-core/src/test/resources/example-types.yml
Labels: merge when ready, no changelog, autorelease

#1966 external imports have safety now
  changelog/@unreleased/pr-1966.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/DangerousLongAlias.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ExternalLongUnionExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SafeExternalLongAlias.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SafeExternalLongExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SafeLongAlias.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UndertowExternalLongTestService.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ExternalLongUnionExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SafeExternalLongAlias.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SafeExternalLongExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/ConjureTags.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/Retrofit2ServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceHandlerGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowTypeFunctions.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DefaultStaticFactoryMethodGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/ReturnTypeMapper.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderAuxiliarySettersUtils.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/DefaultClassNameVisitor.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/ErrorGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/MethodSpecs.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/Parameters.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/SafetyEvaluator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/util/Primitives.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/ConjureTagsTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/ExternalImportSafetyTests.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/SafetyEvaluatorTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/util/SafetyUtilsTests.java
Labels: merge when ready, autorelease

#1970 Require non-null elements in collection body params
  changelog/@unreleased/pr-1970.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/DefaultClassNameVisitor.java
  conjure-undertow-lib/build.gradle
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/generate/ConjureUndertowEndpointsGenerator.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/ConjureUndertowAnnotationProcessorTest.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/CollectionBodyParam.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/CollectionBodyParamEndpoints.java.generated
Labels: merge when ready, autorelease
