Repository palantir/conjure-java, pull requests merged in 2024-03, with the labels that each got.

#2213 Java generator supports ignoring external type imports
  changelog/@unreleased/pr-2213.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/AliasToExternal.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/DialogueServiceUsingExternalTypesEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/ObjectWithExternalField.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/ServiceUsingExternalTypesAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/ServiceUsingExternalTypesBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/UnionWithExternal.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/ExternalImportFilter.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/GenerationCoordinator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/Options.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/ExternalTypeFallbackTests.java
  conjure-java-core/src/test/resources/external-types.yml
  conjure-java/src/main/java/com/palantir/conjure/java/cli/ConjureJavaCli.java
  readme.md
Labels: merge when ready, autorelease

#2216 nullable PlainSerDe#deserializeRid input
  conjure-undertow-lib/src/main/java/com/palantir/conjure/java/undertow/lib/PlainSerDe.java
Labels: merge when ready, no changelog, autorelease

#2225 Fix externalFallbackTypes to also apply to endpoint return types
  changelog/@unreleased/pr-2225.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/ServiceUsingExternalTypes.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/ServiceUsingExternalTypesAsync.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/ServiceUsingExternalTypesBlocking.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/external/ServiceUsingExternalTypesEndpoints.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/ExternalImportFilter.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/ExternalTypeFallbackTests.java
  conjure-java-core/src/test/resources/external-types.yml
Labels: merge when ready, autorelease

#2237 do not attempt to generate a dialog service if no endpoints
  changelog/@unreleased/pr-2237.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DialogueServiceGenerator.java
  conjure-java-core/src/test/resources/example-service.yml
  conjure-java-core/src/test/resources/test/api/TestEmptyService.java.jersey
  conjure-java-core/src/test/resources/test/api/TestEmptyService.java.jersey.jakarta
  conjure-java-core/src/test/resources/test/api/TestEmptyService.java.jersey.prefix
  conjure-java-core/src/test/resources/test/api/TestEmptyService.java.jersey_require_not_null
  conjure-java-core/src/test/resources/test/api/TestEmptyService.java.undertow
  conjure-java-core/src/test/resources/test/api/TestEmptyService.java.undertow.prefix
  conjure-java-core/src/test/resources/test/api/TestEmptyServiceAsync.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestEmptyServiceAsync.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/TestEmptyServiceBlocking.java.dialogue
  conjure-java-core/src/test/resources/test/api/TestEmptyServiceBlocking.java.dialogue.prefix
  conjure-java-core/src/test/resources/test/api/TestEmptyServiceEndpoints.java.undertow
  conjure-java-core/src/test/resources/test/api/TestEmptyServiceEndpoints.java.undertow.prefix
Labels: merge when ready, autorelease

#2264 Expose a TypeMarker factory to wrap an arbitrary Type
  changelog/@unreleased/pr-2264.v2.yml
  conjure-undertow-lib/src/main/java/com/palantir/conjure/java/undertow/lib/TypeMarker.java
Labels: merge when ready, autorelease

#2265 TypeMarker base type declares hashCode/equals contract
  changelog/@unreleased/pr-2265.v2.yml
  conjure-undertow-lib/src/main/java/com/palantir/conjure/java/undertow/lib/TypeMarker.java
Labels: merge when ready, autorelease

#2267 Support providing runtime to param decoders
  changelog/@unreleased/pr-2267.v2.yml
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/Instantiables.java
  conjure-undertow-processor/src/main/java/com/palantir/conjure/java/undertow/processor/data/ParamTypesResolver.java
  conjure-undertow-processor/src/test/java/com/palantir/conjure/java/undertow/processor/sample/DefaultDecoderService.java
  conjure-undertow-processor/src/test/resources/com/palantir/conjure/java/undertow/processor/sample/DefaultDecoderServiceEndpoints.java.generated
Labels: merge when ready, autorelease

#2269 Document support decoders and serializers
  conjure-undertow-annotations/readme.md
Labels: merge when ready, no changelog
