Repository palantir/conjure-java, pull requests merged in 2024-11, with the labels that each got.

#2390 Remove Primitive Optimization for Boolean Collections
  changelog/@unreleased/pr-2390.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ListExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-java-core/src/test/resources/example-types.yml
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureBooleanList.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureCollections.java
Labels: merge when ready

#2401 Support endpoint errors
  build.gradle
  changelog/@unreleased/pr-2401.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/another/EndpointSpecificErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/another/EndpointSpecificServerErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EndpointSpecificErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EndpointSpecificServerErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EndpointSpecificTwoErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EndpointSpecificTwoServerErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ErrorServiceEndpoints.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/TestErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/TestServerErrors.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/UndertowErrorService.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/ServiceGenerators.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceHandlerGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/UndertowServiceInterfaceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/DialogueInterfaceGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/CheckedErrorGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/ErrorGenerator.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/util/ErrorGenerationUtils.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/UndertowServiceEteTest.java
  conjure-java-core/src/test/resources/errors-for-endpoints.yml
  conjure-java-core/src/test/resources/example-endpoint-errors.yml
  conjure-java-undertow-runtime/build.gradle
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureError.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptions.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/ConjureExceptionHandlerTest.java
  conjure-java/src/main/java/com/palantir/conjure/java/cli/ConjureJavaCli.java
  versions.lock
  versions.props
Labels: merge when ready, autorelease

#2415 UnclosableOutputStream passes through BufferWritableOutputStream
  changelog/@unreleased/pr-2415.v2.yml
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/UnclosableOutputStream.java
  conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/UnclosableOutputStreams.java
  conjure-java-undertow-runtime/src/test/java/com/palantir/conjure/java/undertow/runtime/UnclosableOutputStreamTest.java
Labels: merge when ready, autorelease

#2417 [Prework] Landing all 'conjure-lib' API changes Ahead of CodeGen Adoption
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureCollections.java
Labels: merge when ready, no changelog, autorelease
