Repository palantir/conjure-java, pull requests merged in 2025-03, with the labels that each got.

#2472 nit: Make `ReturnTypeMapper` package-private
  changelog/@unreleased/pr-2472.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/services/dialogue/ReturnTypeMapper.java
Labels: merge when ready

#2476 Add All Primitive Collection Types to the Test Example
  conjure-java-core/src/integrationInput/java/primitivecollections/com/palantir/product/PrimitiveExample.java
  conjure-java-core/src/integrationInput/java/strictprimitivecollections/com/palantir/product/PrimitiveStrictExample.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/NonNullCollectionsTest.java
  conjure-java-core/src/test/resources/primitive-collections-strict.yml
  conjure-java-core/src/test/resources/primitive-collections.yml
Labels: merge when ready, no changelog

#2475 New ConjureCollections Methods for Future Optimizations
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureCollections.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureDoubleList.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureIntegerList.java
Labels: merge when ready, no changelog, autorelease

#2480 Add validation for snapshot folder contents
  changelog/@unreleased/pr-2480.v2.yml
  conjure-java-core/src/test/java/com/palantir/conjure/java/parameterized/ParameterizedConjureGenerationTest.java
Labels: merge when ready
