Repository palantir/conjure-java, pull requests merged in 2025-01, with the labels that each got.

#2409 [Improvement] Leverage List Creation Facade for Future Optimizations
  conjure-java-core/src/integrationInput/java/com/palantir/product/CollectionsTestObject.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/CovariantListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ExternalLongExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/MultipleFieldsOnlyFinalStage.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SafeExternalLongExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/SafeLongExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictFourFields.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictMultipleDeprecatedAndUnsafeFields.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictOneCollectionField.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StrictThreeFields.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/CovariantListExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ExternalLongExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/ManyFieldExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SafeExternalLongExample.java
  conjure-java-core/src/integrationInput/java/test/prefix/com/palantir/product/SafeLongExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
Labels: merge when ready, no changelog

#2386 [Feature] Add Serialization Optimization for Primitive Collection Types
  changelog/@unreleased/pr-2386.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/PrimitiveExample.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/NonNullCollectionsTest.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/ObjectGeneratorTests.java
  conjure-java-core/src/test/resources/primitive-collections.yml
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureCollections.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureDoubleList.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureIntegerList.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureSafeLongList.java
Labels: merge when ready

#2389 [Feature] Non-boxing 'addAll' Methods for Primitive Types
  changelog/@unreleased/pr-2389.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/ListExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderAuxiliarySettersUtils.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/SafeLong.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureCollections.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureDoubleList.java
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/internal/ConjureIntegerList.java
Labels: merge when ready

#2431 Optimized Jackson Deserialization for Optimized List of Primitives
  changelog/@unreleased/pr-2431.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/ListExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/PrimitiveExample.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java
Labels: merge when ready, autorelease

#2433 Reduce Optional allocations in SafetyEvaluator
  changelog/@unreleased/pr-2433.v2.yml
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/SafetyEvaluator.java
Labels: merge when ready, autorelease

#2434 [Fix] Restore Mistakenly Removed 'MAX_VALUE' and 'MIN_VALUE'
  changelog/@unreleased/pr-2434.v2.yml
  conjure-lib/src/main/java/com/palantir/conjure/java/lib/SafeLong.java
Labels: merge when ready, autorelease

#2440 [Improvement] Adopt RevAPI
  build.gradle
  conjure-java-undertow-runtime/build.gradle
  conjure-lib/build.gradle
  conjure-undertow-annotations/build.gradle
  conjure-undertow-lib/build.gradle
Labels: merge when ready, no changelog

#2087 Add flag to exclude static factory methods from generated objects
  changelog/@unreleased/pr-2087.v2.yml
  conjure-java-core/src/integrationInput/java/com/palantir/product/CovariantListExampleNoStaticFactory.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/EmptyExample.java
  conjure-java-core/src/integrationInput/java/com/palantir/product/StringExampleNoStaticFactory.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/Options.java
  conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java
  conjure-java-core/src/test/java/com/palantir/conjure/java/types/ObjectGeneratorTests.java
  conjure-java-core/src/test/resources/example-types-no-static-factory.yml
  conjure-java/src/main/java/com/palantir/conjure/java/cli/ConjureJavaCli.java
  readme.md
Labels: merge when ready, autorelease
